[WIP] feat(server): add comments apis
pesto-students/batch-9-Lumen pull request #101
Opened 2019-08-22 09:58 UTC by piyushagwl007

## PR Checklist
Please check that your PR fulfills the following requirements:

- [ ] The commit message follows [our guidelines](https://github.com/pesto-students/batch-9-Lumen/wiki/Commit-message-convention)
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)
- [ ] GIFs/Videos/Images added (only for frontend changes)

## PR Type
What kind of change does this PR introduce? 

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Infrastructure changes
- [ ] Other... Please describe:
Issue Number: 
#

## What is the new behavior?

## Does this PR introduce a breaking change?
- [ ] Yes
- [ ] No

## Other information

2019-08-23 06:44 UTC, nimish-gupta commented on server/src/services/comments/api.js
> +    const comments = await getTenCommentsService(req.blog._id, req.params.page, commentsParentId);
In service instead of hardcoding10, you can pass 10 as argument

2019-08-23 06:45 UTC, nimish-gupta requested changes

2019-08-23 06:45 UTC, nimish-gupta commented on server/src/services/comments/service.js
> +const getTenComments = async (blogId, page = 1, parentId = null) => {
Wrtite tests for this route

2019-08-23 17:29 UTC, karansapolia approved these changes
LGTM

2019-08-24 03:08 UTC, nimish-gupta approved these changes

2019-08-24 03:08 UTC, nimish-gupta commented on server/src/__tests__/routes/comments/index.test.js
> +const blogs = [{
just create a file called test utils and move all this to over there, so you dont have to create the blogs/comments everytime.

2019-08-24 10:01 UTC, nihalanisumit approved these changes
LGTM

2019-08-24 10:01 UTC, nihalanisumit commented on server/src/controller/apis/comments.js
> +router.get('/:id/:page', getBlog, CommentsAPI.getTenComments);
what is page?
Try to name id better, for blog id write blogID and for comment id write commentID

2019-08-25 06:02 UTC, merged